[[Gurobi]]
git-tree-sha1 = "11980007f4c80fcdcbdd8e7b8dafaa8657dcead9"
arch = "x86_64"
os = "linux"

    [[Gurobi.download]]
    sha256 = "df72e6621633f3bb88faa0fd08daa0c0fa84492b9ab20237e4422f23b3898903"
    url = "https://anaconda.org/Gurobi/gurobi/12.0.3/download/linux-64/gurobi-12.0.3-py311_0.tar.bz2"
[[Gurobi]]
git-tree-sha1 = "9ab677b1a86b74c7561876f064c4924e44e53338"
arch = "aarch64"
os = "linux"

    [[Gurobi.download]]
    sha256 = "26b93fd4ef91ef220d1739a321aba3fd023a206a733849d64f5c1708b8db9a8a"
    url = "https://anaconda.org/Gurobi/gurobi/12.0.3/download/linux-aarch64/gurobi-12.0.3-py311_0.tar.bz2"
[[Gurobi]]
git-tree-sha1 = "6128cd989db64bbbce58dd5725bb2990b87f18c9"
arch = "x86_64"
os = "macos"

    [[Gurobi.download]]
    sha256 = "83031cf70526a2d8d5d4d2a500779fea447a3542975401b0ab42dd721de6d447"
    url = "https://anaconda.org/Gurobi/gurobi/12.0.3/download/osx-64/gurobi-12.0.3-py311_0.tar.bz2"
[[Gurobi]]
git-tree-sha1 = "49c8e5760716c69803360127c673c65ea56a65f5"
arch = "aarch64"
os = "macos"

    [[Gurobi.download]]
    sha256 = "1600598d2cc6fe958ac4e56e32d69266020238ce4c4fa1f2f28c81c94101b33c"
    url = "https://anaconda.org/Gurobi/gurobi/12.0.3/download/osx-arm64/gurobi-12.0.3-py311_0.tar.bz2"
[[Gurobi]]
git-tree-sha1 = "b31bf0fecbd28572b2ff8cf05c035350be319a5d"
arch = "x86_64"
os = "windows"

    [[Gurobi.download]]
    sha256 = "d4a3f481e863b30e994d73ef9aaaf91362d6e99cf5d8aa543b87bc89feba453c"
    url = "https://anaconda.org/Gurobi/gurobi/12.0.3/download/win-64/gurobi-12.0.3-py311_0.tar.bz2"
