[[Gurobi]]
git-tree-sha1 = "f0e5f5a89f78144698ed87413adc7743688584f5"
arch = "x86_64"
os = "linux"

    [[Gurobi.download]]
    sha256 = "98455455709e8b34b34032ed90d4bf1246b14f4313a312f7c775066ff5c1f652"
    url = "https://packages.gurobi.com/13.0/gurobi13.0.0_linux64.tar.gz"
[[Gurobi]]
git-tree-sha1 = "8c5a6a5a0da6625f88cd6349d26e910ffe670c9f"
arch = "aarch64"
os = "linux"

    [[Gurobi.download]]
    sha256 = "d301613332cad505620dcd192ccfe855e9ad456d20f8544944514e2ff7a23851"
    url = "https://packages.gurobi.com/13.0/gurobi13.0.0_armlinux64.tar.gz"
[[Gurobi]]
git-tree-sha1 = "df29ce14d0a4a14d0ab2ad6233c0c6a9bb76abce"
arch = "x86_64"
os = "macos"

    [[Gurobi.download]]
    sha256 = "85ac3591eadea53d041fa5b19ba61582c567a43aabfe04e36780c88acf35f36c"
    url = "https://packages.gurobi.com/13.0/gurobi13.0.0_macos_universal2.tar.gz"
[[Gurobi]]
git-tree-sha1 = "df29ce14d0a4a14d0ab2ad6233c0c6a9bb76abce"
arch = "aarch64"
os = "macos"

    [[Gurobi.download]]
    sha256 = "85ac3591eadea53d041fa5b19ba61582c567a43aabfe04e36780c88acf35f36c"
    url = "https://packages.gurobi.com/13.0/gurobi13.0.0_macos_universal2.tar.gz"
[[Gurobi]]
git-tree-sha1 = "5880b5e4612ccf8d60680288f5cbeb8d7429f765"
arch = "x86_64"
os = "windows"

    [[Gurobi.download]]
    sha256 = "7ffd782fe8c8576bd5fdcd8c9a12191dca03606384a47193202b06ac95fffdbb"
    url = "https://packages.gurobi.com/13.0/gurobi13.0.0_win64.tar.gz"
